//tealium universal tag - utag.16313 ut4.0.201604081202, Copyright 2016 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<35){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.ev={"view":1};u.rp=function(a,b){if(typeof a!="undefined"&&a.indexOf(u.t)>0){a=a.replace(/@@([^@]+)@@/g,function(m,d){if(b[d]){return b[d];}else{return'';}});}
return a;};u.map={};u.extend=[function(a,b){if(typeof b._vtrack_command!==(undefined||'undefined')){var pageName='cookieweiche/'+b._vtrack_command;}else{var pageName='cookieweiche/uncaught-origin';b._vtrack_command='uncaught-origin';}
b._vtrack_sica='onedev/1/H.24.2/{random}?AQB=1&ndh=1&vmt=49EAF7F8&pe=lnk_o&pev2=Cookieweiche Visit&gn={pageName}&ce=UTF-8&ns=swisscom&cc=CHF&g={pageURL}&c33=cookieweiche&c34={info_content}&AQE=1'
.replace("{random}",b._timestamp)
.replace("{pageName}",pageName)
.replace("{pageURL}",window.location.protocol+"//"+window.location.host+window.location.pathname)
.replace("{info_content}",b._vtrack_command);}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:16313");utag.DB(b);var c;u.t="@@";u.i=[];u.p=["https://so.swisscom.ch/b/ss/swisscom-@@_vtrack_sica@@","","","","","","",""];u.delim="";u.cachebust="disabled";u.cachevar=""||"_rnd";for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(c=0;c<u.p.length;c++){if(u.p[c]!=""){var x=u.rp(u.p[c],b);if(x!=""){if(u.cachebust=="enabled"&&x.indexOf(u.cachevar)<0){if(x.indexOf("?")<0){u.delim="?";}else{u.delim="&";}
x+=u.delim+u.cachevar+"="+Math.random();}
var img=new Image();img.src=x;u.i.push(img);}}}}};utag.o[loader].loader.LOAD(id);}("16313","swisscom.main"));}catch(error){utag.DB(error);}
